### ISSUE TITLE
Doesn't build on Windows

### ISSUE THREAD

**Issue by CremboC** [depressed-pho/bitstream#5]
```
Data\Bitstream\Lazy.hs:692:1: error:
    Rule "Lazy Bitstream unstreamChunks/streamChunks fusion":
        Illegal expression: unId
        in left-hand side: unId (unstreamChunks (streamChunks
    LHS must be of form (f e1 .. en) where f is not forall'd
```
Is the error I get upon `cabal install bitstream`. I know this library hasn't been updated in 2 years, but would be nice to try it out (unless you have an alternative).

PS. I'm on the newest Haskell platform (8.0.1)

**Comment by Ofenhed** [comment]
Doesn't build on Linux either.

**Comment by chipbuster** [comment]
Won't build on MacOS, Haskell Platform 8.0.2

**Comment by romhack** [comment]
Doesn't build on latest stack either.

**Comment by mayeranalytics** [comment]
Using `stack` you can do this:

```bash
git clone git@github.com:depressed-pho/bitstream.git
cd bitstream 
stack init
```
`stack init` searches through the snapshots and finds a match with `lts-3.22` (Jan 2016).

Then `stack build` will download the old-ish`ghc-7.10.2` and compiles it all without errors (but one warning). The tests (via `stack test`) compile fine (apart from some warnings, again) and do pass .

**Comment by chipbuster** [comment]
I was able to build this into a stack project by specifying the `lts-3.22` resolver and adding `bitstream-0.2.0.4` into the `extra-deps` field in `stack.yaml`, as well as adding `bitstream` to the requirements in `package.yaml`

Bit of a bummer that it basically forces the use of 2-year-old packages, but it at least appears to work.
